version: '3.8'
services:
  db:
    image: percona:5.7
    container_name: payroll_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=payroll
      - MYSQL_DATABASE=payroll
      - MYSQL_USER=payroll
    ports:
      - '3307:3306'
    volumes:
      - ./var/lib/mysql:/var/lib/mysql

  php:
    container_name: payroll_php
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/app
    depends_on:
      - db

  nginx:
    container_name: payroll_nginx
    image: nginx:stable-alpine
    ports:
      - '4200:80'
    volumes:
      - ./:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
